### ISSUE TITLE
NA value in the results

### ISSUE THREAD

**Issue by Lin13432** [lhe17/nebula#52]
Dear all,

When I see the result$summary, I noticed that some gene only have values for logFC, but have NA for all se or pvalue columns, these genes seem to have large logFC usually, may I ask why this happen?
![image](https://github.com/user-attachments/assets/68281342-1149-49a2-86f8-db3957adb9f7)

another question is that I found the logFC and pvalue of each gene are quiet different from nebula to other psudobulk DE analysis, and the the volcano plot looks weird because large logFC does not show a positive relationship with  -log10(FDR), here I calculate FDR by myself, may I ask why?
![Aged_ctrl_KD_vs_Aged_exenatide_KD_volcano](https://github.com/user-attachments/assets/ff9e8401-1c10-4507-b11d-ed7d3f37463c)

**Comment by lhe17** [comment]
Thank you for your question.
An NA in SE or p value is because the optimization algorithm has a
convergence problem for this gene, usually with a convergence code -25. It
indicates that there is a separation issue and maximum likelihood
estimation fails. See also https://github.com/lhe17/nebula/issues/18. The
next version will have a better option to this issue.

I'm not sure why the results are not consistent and the volcano plot looks
strange.

Best regards,
Liang
